// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://touskbbyvzakndpkykut.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvdXNrYmJ5dnpha25kcGt5a3V0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0Mjg3ODEsImV4cCI6MjA1OTAwNDc4MX0.xW3yX7DxE4SZwa2zgwdZsFKXwT5fUmjx63wLiBnaCxI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);